### ISSUE TITLE
"make bootstrap" command error

### ISSUE THREAD

**Issue by SpeakyDre** [microfeatures/example#2]
Hi,

I am going through the steps to setup the project.
When doing a "make bootstrap", I get the following error:
```
bundle install
make: bundle: No such file or directory
make: *** [bootstrap] Error 1
```

Could you help me with that please?

Thank you.

**Comment by johneris** [comment]
I'm having the same error.

**Comment by PeterGumball** [comment]
@SpeakyDre @johneris 

Please install bundler:
`gem install bundler`

**Comment by johneris** [comment]
Thanks @PeterGumball !

**Comment by SpeakyDre** [comment]
Thanks @PeterGumball
